= Release notes v. 5.2

== Table of Contents
* Bugfix: wrong scaStatus after consent authorisation with zero sca methods for Embedded approach
* Support country specific extensions for payments in the ASPSP profile
* Support Additional Account Information in AIS

== Bugfix: wrong scaStatus after consent authorisation with zero sca methods for Embedded approach

From now on when you read SCA status of the consent authorisation with zero SCA methods,
you'll receive response `{"scaStatus": "failed"}`.

== Support country specific extensions for payments in the ASPSP profile

From now on, ASPSP is able to configure payment for different countries `countryValidationSupported` property in PIS block.
The configuration parameter takes country as ISO 3166-1 alpha-2 code (DE, AT, UA, etc). Germany (DE) is supported by default and Austria (AT) is available to choose from.
Previous validation payment configuration in `application.yml` file has been removed.

== Support Additional Account Information in AIS

From now on, Additional Account Information is supported in AIS.
There is new `SpiAdditionalInformationAccess` field In `SpiAccountConsent` object in `SpiAccountAccess` block which represents TPP desire
to retrieve additional information (`ownerName` and `ownerAddress`) about PSU by it's account reference.
This information ASPSP can provide through `ownerName` and `ownerAddress` fields in `SpiAccountDetails` object,
during invoking `requestAccountList` or `requestAccountDetailForAccount` methods in AccountSpi.