= Release notes v. 5.8

== Table of Contents

* Allow custom payment validation
* Migrate to common payment object
* Fixed incorrect response for creating AIS consent or payment with wrong `IBAN`

== Allow custom payment validation

From now on, XS2A allows to validate custom country-specific payments.
Payment body and payment business validators were affected by this changes.
To configure validation for another country, SPI developer should provide custom implementation of `de.adorsys.psd2.validator.payment.CountryValidatorHolder` interface.

== Migrate to common payment object

From now on, XS2A is switching to using common payment object instead of type-specific payments (single, periodic and bulk).
Common payment is stored in CMS and transferred to SPI as byte array without parsing specific fields, just as it was received from TPP.
To provide backward compatibility for previous versions new module was added:

[source]
----
<dependency>
    <groupId>de.adorsys.psd2</groupId>
    <artifactId>cms-payment-support-impl</artifactId>
</dependency>
----

It should be added as a dependency to custom CMS application for mapping common payment to existing type-specific payment models.

To handle only common payments, previously mentioned dependency should be replaced with the following one:

[source]
----
<dependency>
    <groupId>de.adorsys.psd2</groupId>
    <artifactId>cms-payment-common-impl</artifactId>
</dependency>
----

In case of using common implementations, all payments will be forwarded to `CommonPaymentSpi`.

== Fixed incorrect response for creating AIS consent or payment with wrong `IBAN`

From now on, when you try to create consent or payment with `IBAN` which is wrong for `PSU ID`, you'll get an error
`FORMAT_ERROR` with text `Addressed account is unknown to the ASPSP or not associated to the PSU`.