= Release notes v. 5.1

== Table of Contents
* SCA exemption is supported
* Refactor: Aggregate all messages sent to TPP to message bundle
* Bugfix: Incorrect response for Get Payment Information request

== SCA exemption is supported

From now on, SCA exemption is possible for bulk and single payment initiation. To support this, return type of
`AuthorisationSpi#authorisePsu` method was changed from `SpiAuthorisationStatus` to `SpiPsuAuthorisationResponse`.
`SpiPsuAuthorisationResponse` is a new domain class, which contains authorisation status as well as boolean `scaExempted`
field, which is taken into account by XS2A for performing SCA exemption. If the psu authorisation spi response for
bulk or single will be successful and `scaExempted` is `true` - SCA will not be performed, 'PaymentSpi#executePaymentWithoutSca'
will be invoked and authorisation status will be set to `EXEMPTED`. SCA exemption is supported for multilevel SCA too.

== Refactor: Aggregate all messages sent to TPP to message bundle

From now on all text messages for TPP are aggregated in `error_message.properties` file. These messages are executed by
`Psd2ErrorMapper`. Also from now on class `TppMessageInformation` has new array field `textParameters` for keeping
values, which should be inserted into message text placeholders for TPP from `error_message.properties`.

== Bugfix: Incorrect response for Get Payment Information request

From now on, Get Payment Information request `GET /v1/{payment-service}/{payment-product}/{paymentId}`
returns correct response with payment in body.