---
# yamllint disable rule:line-length
# ------------------------------------------------------------------
# Global settings
# ------------------------------------------------------------------

image: "adorsys/ci-build:latest"

# ------------------------------------------------------------------
# stages
# ------------------------------------------------------------------

stages:
  - "Lint"
  - "Compile"    # build jar and provide as artifact
  - "Test"       # run tests and code quality checks
  - "Package"    # dockerize jar and push to docker registry
  - "Deployment" # push to openshift registry (snapshot Deploymentment) or release registry

# ------------------------------------------------------------------
# variables
# ------------------------------------------------------------------

variables: &variables
  SONAR_HOST: "https://psd2-quality.cloud.adorsys.de"

  ###########################
  # Docker images variables #
  ###########################

  DOCKER_IMAGE_NAME_XS2A_CONNECTOR: "adorsys/xs2a-connector-examples"
  DOCKER_IMAGE_NAME_XS2A_CONNECTOR_EMBEDDED: "adorsys/xs2a-connector-embedded"

  ###########################
  # Build variables         #
  ###########################

  JAVA_TOOL_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:MaxRAM=3G -XX:MaxRAMFraction=3"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

  ############################
  # Private Openshift Images #
  ############################

  OPENSHIFT_NAMESPACE_SUPPORT8X: adorsys-psd2-support8x

# ------------------------------------------------------------------
# reusable yaml anchors
# ------------------------------------------------------------------

# Build docker images and put them to DOCKER HUB repo
.build_dockerhub_image: &build_dockerhub_image
  script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS
    - docker build -t "adorsys/xs2a-connector-examples:$DOCKER_TAG" gateway-app
    - docker push "adorsys/xs2a-connector-examples:$DOCKER_TAG"
    - docker logout

# Build docker image xs2a-connector separately and put them to DOCKER HUB repo
.build_dockerhub_image_embedded: &build_dockerhub_image_embedded
  script:
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASS
    - docker build -t "adorsys/xs2a-connector-embedded:$DOCKER_TAG" gateway-app-embedded
    - docker push "adorsys/xs2a-connector-embedded:$DOCKER_TAG"
    - docker logout

.deploy_openshift: &deploy_openshift
  script:
    - >-
      skopeo copy
      --dest-creds=openshift:${OPENSHIFT_TOKEN}
      "docker://docker.io/adorsys/xs2a-connector-examples:${DOCKER_TAG}"
      "docker://${OPENSHIFT_REGISTRY}/${OPENSHIFT_NAMESPACE}/xs2a-connector-examples:latest"

# ------------------------------------------------------------------
# jobs
# ------------------------------------------------------------------

#-------------------------------------------------------------------
# lint
#-------------------------------------------------------------------

Lint:Docker_compose:
  image: maven:3.6-jdk-11-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt update && apt install yamllint docker-compose make -yq
    - echo "Run Docker compose lint"
    - docker-compose -f docker-compose.yml config  -q

Lint:Ci_file:
  image: debian:stretch-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt-get update && apt-get install yamllint python3-pkg-resources -yq
    - echo "Run Gitlab ci file lint"
    - yamllint -d relaxed .gitlab-ci.yml

Lint:XS2A_connector_yaml_json_xml:
  image: debian:stretch-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt-get update && apt-get install jsonlint yamllint libxml2-utils make curl -yq && ln -s /usr/bin/jsonlint-php /usr/bin/jsonlint
    - echo "Run Xs2A core lint"
    - find ./ -type f -name "*.json" -exec jsonlint -q {} \; # lint all json
# commented cause get many small errors for yaml with spaces empty lines and etc
#    - find ./ -type f \( -name "*.yml" -o -name "*.yaml" \) -exec yamllint -d "{extends: relaxed, rules: {line-length: {max: 160}}}" {} \;
# commented cause get error Unsupported version '1.1'
#	  - find ./ -type f \( -iname "*.xml" ! -iname pom.xml \) -exec xmllint --noout {} \;

Lint:XS2A_connector_PMD_CPD_Report:
  image: maven:3.6-jdk-11-slim
  stage: "Lint"
  except:
    - schedules
    - develop
    - master
  script:
    - apt update && apt install make -yq
    - echo "Test java code for PMD and CPD"
    - mvn -ntp -Dmaven.test.skip=true package pmd:check # commented cause many duplications pmd:cpd-check
  cache: {}
  artifacts:
    paths:
      - "qa/pmd/pmd-ruleset.xml"
      - "**/**/*/pmd.html"
      - "**/*/pmd.xml"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}-pmd"
    expire_in: "10 day"

Lint:XS2A_connector_dockerfiles:
  image: docker:20.10
  stage: "Lint"
  services:
    - docker:20.10-dind
  except:
    - schedules
    - develop
    - master
  script:
    - echo "Run Xs2a connector dockerfile checks"
    - docker run --rm -i hadolint/hadolint < ./gateway-app/Dockerfile
    - docker run --rm -i hadolint/hadolint < ./gateway-app-embedded/Dockerfile

#-------------------------------------------------------------------
# Compile
#-------------------------------------------------------------------

Build:XS2A_connector_Java11:
  stage: "Compile"
  script:
    - jabba use "system@1.11"
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -DskipITs -DskipTests -Dci.build.number=Build\:${CI_PIPELINE_ID} clean install
  artifacts:
    paths:
      - "gateway-app/target/gateway-app*jar"
      - "gateway-app-embedded/target/gateway-app*jar"
      - "ledgers-rest-client/target/ledgers-rest-client*jar"
      - "xs2a-connector/target/xs2a-connector*jar"
      - "**/target/*"
      - "**/**/target/*"
      - ".m2/repository/de/adorsys/ledgers/*/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}"
    expire_in: "10 day"

#-------------------
# Test
#-------------------

Test:Javadoc Java11:
  stage: "Test"
  script:
    - jabba use "system@1.11"
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -Dmaven.test.skip=true package javadoc:javadoc
  artifacts:
    paths:
      - "**/target/site/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-javadoc"
    expire_in: "10 day"

Test:UI_Tests_Java11:
  stage: "Test"
  script:
    - jabba use "system@1.11"
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -DskipITs --fail-at-end clean install
  artifacts:
    paths:
      - "**/target/surefire-reports/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-*"
    expire_in: "10 day"

Test:IT_Java11:
  stage: "Test"
  script:
    - jabba use "system@1.11"
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp failsafe:integration-test failsafe:verify
  variables:
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"

Test:DOCKER_test_image_build:
  stage: "Test"
  script:
    - docker build -t "adorsys/xs2a-connector-examples:test" gateway-app
    - docker build -t "adorsys/xs2a-connector-embedded:test" gateway-app-embedded

Test:Sonarcube:
  stage: "Test"
  needs: []
  except:
    - schedules
    - develop
  script:
    - jabba use "system@1.11"
    - cat /sys/fs/cgroup/memory/memory.limit_in_bytes
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn --fail-at-end clean install
    - mvn sonar:sonar -Dsonar.host.url=$SONAR_HOST -Dsonar.login=${SONAR_TOKEN}
  only:
    - develop

###########
# Support 8.x #
###########

Push to DockerHub (support-8.x):
  stage: "Package"
  only:
    - support-8.x
  variables:
    DOCKER_TAG: support8x
  <<: *build_dockerhub_image

Deploy Openshift (support-8.x):
  stage: "Deployment"
  only:
    - support-8.x
  variables:
    <<: *variables
    DOCKER_TAG: support8x
    OPENSHIFT_NAMESPACE: "${OPENSHIFT_NAMESPACE_SUPPORT8X}"
  <<: *deploy_openshift

###########
# release #
###########

Push to DockerHub (Release):
  stage: "Package"
  only:
    - tags
  variables:
    DOCKER_TAG: $CI_COMMIT_TAG
  <<: *build_dockerhub_image
