---
# yamllint disable rule:line-length
# ------------------------------------------------------------------
# Global settings
# ------------------------------------------------------------------

image: "adorsys/ci-build:latest"

# ------------------------------------------------------------------
# stages
# ------------------------------------------------------------------

stages:
  - "Lint"
  - "Compile"    # build jar and provide as artifact
  - "Test"       # run tests and code quality checks
  - "Package"    # dockerize jar and push to docker registry
  - "Release"    # release
  - "Clone to github"
# ------------------------------------------------------------------
# variables
# ------------------------------------------------------------------

variables:

  ###########################
  # Docker images variables #
  ###########################

  DOCKER_IMAGE_NAME_XS2A_CONNECTOR: "xs2a-connector-examples"
  DOCKER_IMAGE_NAME_XS2A_CONNECTOR_EMBEDDED: "xs2a-connector-embedded"

  ###########################
  # Build variables         #
  ###########################

  JAVA_TOOL_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:MaxRAM=3G -XX:MaxRAMFraction=3"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# ------------------------------------------------------------------
# reusable yaml anchors
# ------------------------------------------------------------------

.build_and_push_dockerhub_images_private: &build_and_push_dockerhub_images_private
  script:
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A_CONNECTOR}:${DOCKER_TAG}" gateway-app
    - docker build -t "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A_CONNECTOR_EMBEDDED}:${DOCKER_TAG}" gateway-app-embedded
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A_CONNECTOR}:${DOCKER_TAG}"
    - docker push "${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${DOCKER_IMAGE_NAME_XS2A_CONNECTOR_EMBEDDED}:${DOCKER_TAG}"
    - docker logout

.release_java_private: &release_java_private
  stage: "Release"
  script:
    - jabba use $BUILD_JAVA_VERSION
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -ntp --settings scripts/mvn-release-settings.xml -Pgitlab-maven -DskipTests -U deploy
  cache:
    key: "Java_${CI_COMMIT_REF_SLUG}"
    paths:
      - /builds/adorsys/xs2a/xs2a-conector-examples/.m2/repository

.sync_changes_github: &sync_changes_github
  image: alpine/git
  dependencies: []
  script:
    - git config --global user.name "$GITHUB_USERNAME"
    - git remote add github https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git #Token expires on Sat, 11.05.2024
    - for branch in $(git branch -r | grep -E "origin/.*(release-${GITHUB_PROJECT_CLONE_VERSION}.*|support-${GITHUB_PROJECT_CLONE_VERSION}.x).*"); do
        branch=${branch#origin/};
        git checkout $branch;
        git push github $branch --force;
      done
# ------------------------------------------------------------------
# jobs
# ------------------------------------------------------------------

#-------------------------------------------------------------------
# Lint
#-------------------------------------------------------------------

Lint (Docker compose):
  image: maven:3.6-jdk-11-slim
  stage: "Lint"
  except:
    - schedules
    - support-14.x
    - master-14.x
  script:
    - apt update && apt install yamllint docker-compose make -yq
    - echo "Run Docker compose lint"
    - docker-compose -f docker-compose.yml config  -q

Lint (CI):
  image: debian:stable-slim
  stage: "Lint"
  except:
    - schedules
    - support-14.x
    - master-14.x
  script:
    - apt-get update && apt-get install yamllint python3-pkg-resources -yq
    - echo "Run Gitlab ci file lint"
    - yamllint -d relaxed .gitlab-ci.yml

Lint (YAML, JSON, XML):
  image: debian:stable-slim
  stage: "Lint"
  except:
    - schedules
    - support-14.x
    - master-14.x
  script:
    - apt-get update && apt-get install jsonlint yamllint libxml2-utils make curl -yq && ln -s /usr/bin/jsonlint-php /usr/bin/jsonlint
    - echo "Run Xs2A core lint"
    - find ./ -type f -name "*.json" -exec jsonlint -q {} \; # lint all json
# commented cause get many small errors for yaml with spaces empty lines and etc
#    - find ./ -type f \( -name "*.yml" -o -name "*.yaml" \) -exec yamllint -d "{extends: relaxed, rules: {line-length: {max: 160}}}" {} \;
# commented cause get error Unsupported version '1.1'
#	  - find ./ -type f \( -iname "*.xml" ! -iname pom.xml \) -exec xmllint --noout {} \;

Lint (PMD CPD):
  image: maven:3.6-jdk-11-slim
  stage: "Lint"
  except:
    - schedules
    - support-14.x
    - master-14.x
  script:
    - apt update && apt install make -yq
    - echo "Test java code for PMD and CPD"
    - mvn --settings scripts/mvn-release-settings.xml -ntp -Dmaven.test.skip=true package pmd:check # commented cause many duplications pmd:cpd-check
  cache: {}
  artifacts:
    paths:
      - "qa/pmd/pmd-ruleset.xml"
      - "**/**/*/pmd.html"
      - "**/*/pmd.xml"
    name: "${CI_PROJECT_NAME}-${CI_BUILD_REF_NAME#*v}-pmd"
    expire_in: "10 day"

Lint (Dockerfiles):
  image: docker
  stage: "Lint"
  services:
    - docker:dind
  tags:
    - aws
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  except:
    - schedules
    - support-14.x
    - master-14.x
  script:
    - echo "Run Xs2a connector dockerfile checks"
    - docker run --rm -i hadolint/hadolint < ./gateway-app/Dockerfile
    - docker run --rm -i hadolint/hadolint < ./gateway-app-embedded/Dockerfile

#-------------------------------------------------------------------
# Compile
#-------------------------------------------------------------------

Build (XS2A Connector):
  stage: "Compile"
  script:
    - jabba use "system@1.11"
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn -DskipITs -DskipTests --settings scripts/mvn-release-settings.xml -Dci.build.number=Build\:${CI_PIPELINE_ID} clean install
  artifacts:
    paths:
      - "gateway-app/target/gateway-app*jar"
      - "gateway-app-embedded/target/gateway-app*jar"
      - "ledgers-rest-client/target/ledgers-rest-client*jar"
      - "xs2a-connector/target/xs2a-connector*jar"
      - "**/target/*"
      - "**/**/target/*"
      - ".m2/repository/de/adorsys/ledgers/*/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}"
    expire_in: "10 day"

#-------------------
# Test
#-------------------

Test (Javadoc):
  stage: "Test"
  script:
    - jabba use "system@1.11"
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn --settings scripts/mvn-release-settings.xml -Dmaven.test.skip=true package javadoc:javadoc
  artifacts:
    paths:
      - "**/target/site/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-javadoc"
    expire_in: "10 day"

Test (Unit Tests):
  stage: "Test"
  script:
    - jabba use "system@1.11"
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn --settings scripts/mvn-release-settings.xml -DskipITs --fail-at-end clean install
  artifacts:
    paths:
      - "**/target/surefire-reports/*"
    name: "$CI_PROJECT_NAME-${CI_BUILD_REF_NAME#*v}-*"
    expire_in: "10 day"

Test (IT):
  stage: "Test"
  script:
    - jabba use "system@1.11"
    - java -XX:+PrintFlagsFinal -version | grep -Ei "maxheapsize|maxram"
    - mvn --settings scripts/mvn-release-settings.xml -ntp failsafe:integration-test failsafe:verify
  variables:
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"

################
# Package
################

Build and push images to private repo (support14x):
  stage: "Package"
  # except:
  #   - schedules
  only:
    - support-14.x
  services:
    - docker:dind
  tags:
    - aws
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_TAG: support14x
    DOCKERHUB_REGISTRY: gitlab-registry.adorsys.de
    DOCKERHUB_NAMESPACE: "adorsys/xs2a/xs2a-connector-examples"
  <<: *build_and_push_dockerhub_images_private


Build and push images to private repo (tags):
  stage: "Package"
  only:
    - tags
  services:
    - docker:dind
  tags:
    - aws
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_TAG: $CI_COMMIT_TAG
    DOCKERHUB_REGISTRY: gitlab-registry.adorsys.de
    DOCKERHUB_NAMESPACE: "adorsys/xs2a/xs2a-connector-examples"
  <<: *build_and_push_dockerhub_images_private

###########
# Release #
###########

Release snapshot artifacts (support-14.x):
  stage: "Release"
  only:
    - support-14.x
  except:
    - schedules
  cache: {}
  variables:
    BUILD_JAVA_VERSION: system@1.11
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
  <<: *release_java_private

Release snapshot artifacts (tags):
  stage: "Release"
  only:
    - tags
  except:
    - schedules
  cache: {}
  variables:
    BUILD_JAVA_VERSION: system@1.11
    JAVA_TOOL_OPTIONS: "-Djavax.net.ssl.trustStorePassword=changeit -XX:MaxRAM=3G"
  <<: *release_java_private

Clone to github:
  stage: "Clone to github"
  image: alpine/git:latest
  only:
    - support-14.x
    - /^release-14\..*/
  except:
    - schedules
  variables:
    GITHUB_REPOSITORY: adorsys/xs2a-connector-examples
    GITHUB_PROJECT_CLONE_VERSION: "14"
  <<: *sync_changes_github
