version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-connector-data:

services:

  # Xs2a connector example
  xs2a-connector-examples:
    image: adorsys/xs2a-connector-examples:develop
    container_name: xs2a-connector-examples
    restart: on-failure
    ports:
      - "8089:8089"
      - "8189:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=mock-qwac
      - ASPSP-PROFILE_BASEURL=http://xs2a-aspsp-profile:8080/api/v1
      - CONSENT-SERVICE_BASEURL=http://xs2a-consent-management:8080/api/v1
      - LEDGERS_URL=http://ledgers:8088
    networks:
      - xs2a-net
    depends_on:
      - xs2a-aspsp-profile
      - xs2a-consent-management
      - ledgers

  # Xs2a aspsp profile
  xs2a-aspsp-profile:
    image: adorsys/xs2a-aspsp-profile:2.0.1
    container_name: xs2a-aspsp-profile
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx256M"
      - SPRING_PROFILES_ACTIVE=debug_mode
    ports:
      - "48080:8080"
    networks:
      - xs2a-net

  # Consent management
  xs2a-consent-management:
    image: adorsys/xs2a-consent-management:2.0.1
    container_name: xs2a-consent-management
    restart: on-failure
    ports:
      - "38080:8080"
    networks:
      - xs2a-net
    environment:
      - ASPSP-PROFILE_BASEURL=http://xs2a-aspsp-profile:8080/api/v1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent
      - SPRING_DATASOURCE_USERNAME=cms
      - SPRING_DATASOURCE_PASSWORD=cms
      - SERVER_KEY=ledgers_conenctor_secret
      - LIQUIBASE_ENABLED=true
    depends_on:
      - xs2a-consent-management-db

  # Xs2a consent management DB
  xs2a-consent-management-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a-consent-management-db
    restart: on-failure
    volumes:
      - xs2a-connector-data:/var/lib/pgsql/data
      - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - xs2a-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=consent
      - POSTGRESQL_USER=cms
      - POSTGRESQL_PASSWORD=cms

  # Xs2a online banking backend
  xs2a-online-banking:
    image: adorsys/xs2a-online-banking
    container_name: xs2a-online-banking
    restart: on-failure
    ports:
      - "8090:8090"
      - "8190:8000"
    depends_on:
      - ledgers
      - xs2a-connector-examples
    networks:
      - xs2a-net
    environment:
      - XS2A_URL=http://xs2a-connector-examples:8089
      - LEDGERS_URL=http://ledgers:8088

  # Ledgers
  ledgers:
    image: adorsys/ledgers:0.3
    container_name: ledgers
    restart: on-failure
    networks:
      - xs2a-net
    ports:
      - "8088:8088"
      - "8188:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_JPA_SHOW_SQL=false
      - DB_HOST=xs2a-consent-management-db
      - DB_URL=jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=ledgers
      - DB_DATABASE=consent
      - DB_USER=cms
      - DB_PASSWORD=cms
      - LIQUIBASE_ENABLED=true
      - LEDGERS_MOCKBANK_DATA_LOAD=true
    volumes:
      - xs2a-connector-data:/var/lib/data