version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-connector-data:

services:

  xs2a-connector-examples:
    image: adorsys/xs2a-connector-examples
    container_name: xs2a-connector-examples
    restart: on-failure
    ports:
    - "8089:8089"
    - "8189:8000"
    environment:
    - LEDGERS_URL=http://ledgers:8088
    - SPRING_PROFILES_ACTIVE=postgres,mock-qwac
    - DB_HOST=xs2a_connector_examples_db
    - DB_DATABASE=consent
    - DB_USER=cms
    - DB_PASSWORD=cms
    networks:
    - xs2a-net
    depends_on:
    - xs2a-connector-examples-db
    - ledgers


  ledgers:
    image: adorsys/ledgers
    container_name: ledgers
    restart: on-failure
    networks:
    - xs2a-net
    ports:
    - "8088:8088"
    - "8188:8000"
    depends_on:
    - xs2a-connector-examples-db
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - DB_HOST=xs2a-connector-examples-db
      - DB_DATABASE=consent
      - DB_USER=cms
      - DB_PASSWORD=cms

  xs2a-connector-examples-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a_connector_examples_db
    restart: on-failure
    volumes:
    - xs2a-connector-data:/var/lib/pgsql/data
    - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
    - 5432
    ports:
    - "5436:5432"
    networks:
    - xs2a-net
    environment:
    - POSTGRESQL_ADMIN_PASSWORD=postgres
    - POSTGRESQL_DATABASE=consent
    - POSTGRESQL_USER=cms
    - POSTGRESQL_PASSWORD=cms