version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-gateway-data:

services:

  gateway:
    container_name: ledgers-xs2a-gateway-app
    build:
      context: .
      dockerfile: Dockerfile.gateway
    restart: on-failure
    ports:
    - "8089:8089"
    - "8000:8000"
    environment:
    - SPRING_PROFILES_ACTIVE=mock-qwac
    - LEDGERS_URL=http://ledgers:8088
    - ASPSP_PROFILE_BASEURL=http://profile:48080/api/v1
    - CONSENT_SERVICE_BASEURL=http://consent:38080
    - SECURITY_BASIC_ENABLED=false
    networks:
    - xs2a-net
    depends_on:
    - profile
    - ledgers
    - consent

  profile:
    container_name: ledgers-xs2a-profile-app
    build:
      context: .
      dockerfile: Dockerfile.profile
    restart: on-failure
    ports:
    - "48080:48080"
    networks:
    - xs2a-net
    environment:
    - SECURITY_BASIC_ENABLED=false

  consent:
    container_name: ledgers-xs2a-consent-app
    build:
      context: .
      dockerfile: Dockerfile.consent
    restart: on-failure
    ports:
    - "38080:38080"
    - "38000:8000"
    environment:
    - ASPSP_PROFILE_BASEURL=http://profile:48080/api/v1
    - SPRING_PROFILES_ACTIVE=h2
    - DB_URL=jdbc:h2:/var/lib/data/xs2adbs/consent;DB_CLOSE_DELAY=-1
    - DB_USER=sa
    - DB_PASSWORD=sa
    - SECURITY_BASIC_ENABLED=false
    volumes:
    - xs2a-gateway-data:/var/lib/data
    networks:
    - xs2a-net
    depends_on:
    - profile

  ledgers:
    container_name: ledgers-xs2a-app
    build:
      context: .
      dockerfile: Dockerfile.ledgers
    restart: on-failure
    ports:
    - "8088:8088"
    depends_on:
    - fakesmtp
    environment:
    - SPRING_PROFILES_ACTIVE=h2
    - DB_URL=jdbc:h2:/var/lib/data/xs2adbs/ledgers;DB_CLOSE_DELAY=-1
    - DB_USER=sa
    - DB_PASSWORD=sa
    - LEDGERS_MOCKBANK_DATA_LOAD=true
    - SPRING_MAIL_HOST=fakesmtp
    volumes:
    - xs2a-gateway-data:/var/lib/data
    networks:
    - xs2a-net

  fakesmtp:
    container_name: ledgers-fakesmtp-app
    build:
      context: .
      dockerfile: Dockerfile.fakesmtp
    image: adorsys/ledgers-fakesmtp-app:latest
    restart: on-failure
    ports:
    - "2500:2500"
    networks:
    - xs2a-net
    volumes:
    - xs2a-gateway-data:/var/lib/data
    