FROM adorsys/openjdk-jre-base:8-minideb

MAINTAINER https://github.com/adorsys/xs2a-connector-examples

ENV SERVER_PORT 38080
ENV JPDA_ADDRESS 8000

WORKDIR /opt/consent-management-server

COPY ./target/consents/consent-management-server.jar /opt/consent-management-server/consent-management-server.jar
COPY ./src/test/resources/consent-management-application.yml /opt/consent-management-server/consent-management-application.yml

EXPOSE 38080 8000

CMD exec $JAVA_HOME/bin/java -Xmx1024m -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n -jar /opt/consent-management-server/consent-management-server.jar --spring.profiles.active=h2 —security.basic.enabled=false --spring.config.location=/opt/consent-management-server/consent-management-application.yml