FROM adorsys/openjdk-jre-base:8-minideb

MAINTAINER https://github.com/adorsys/xs2a-connector-examples

ENV SERVER_PORT 8089
ENV JPDA_ADDRESS 8000

WORKDIR /opt/gateway-app

COPY ./target/gateway/gateway-app.jar /opt/gateway-app/gateway-app.jar

EXPOSE 8089 8000

CMD exec $JAVA_HOME/bin/java -Xmx1024m -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n -jar /opt/gateway-app/gateway-app.jar
