#
# Copyright 2018-2018 adorsys GmbH & Co KG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000
  use-forward-headers: true
  port: 8089

# Swagger configuration location.
# Empty string, mean the default setting from xs2a-impl will be used.
xs2a.swagger.psd2.api.location: #/psd2-api-1.2-Update-2018-08-18-non-oauth.yaml

#TanEncryption
application:
  security:
    masterPassword: 12345
    encryptorAlgorithm: testAlgorithm

spring:
  application.name: ledgers-xs2a-gateway
  jackson:
    serialization:
      write_dates_as_timestamps: false
      wrap-root-value: true
  datasource:
    url: jdbc:postgresql://localhost/consent
    username: cms
    password: cms
  jpa:
    properties:
      hibernate:
        default_schema: consent

ledgers.url: http://localhost:8088
cms.url: http://localhost:38080
online-banking.url: http://localhost:8090/api/v1/consents/confirm/{userLogin}/{consentId}/{authorizationId}/{tan}

# ----------------------------------------------
# number of characters in a json string
application.ais.transaction.max-length: 1000

#LOGGER
logging.level.org.springframework.web: ERROR

license.url: https://github.com/adorsys/xs2a/blob/master/LICENSE.md
springfox.documentation.swagger.v2.path: /swagger.json

skip.ssl.certificate.verification: true

# ENDPOINTS CORS CONFIGURATION
# Whether credentials are supported. When not set, credentials are not supported.
xs2a:
  endpoints:
    cors:
      allow-credentials: false
      # Comma-separated list of origins to allow. '*' allows all origins. When not set, CORS support is disabled.
      allowed-origins: '*'
      # Comma-separated list of headers to include in a response.
      allowed-headers: '*'
      # Comma-separated list of methods to allow. '*' allows all methods. When not set, defaults to GET.
      allowed-methods: DELETE,GET,OPTIONS,PATCH,POST,PUT
      # How long, in seconds, the response from a pre-flight request can be cached by clients
      max-age: 3600

validation:
  payment:
    endToEndIdentification:
      maxLength: 35
    ultimateDebtor:
      maxLength: 70
    ultimateCreditor:
      maxLength: 70
    streetName:
      maxLength: 100
    buildingNumber:
      maxLength: 20
    townName:
      maxLength: 100
    postCode:
      maxLength: 5
    pan:
      maxLength: 35
    maskedPan:
      maxLength: 35
    msisdn:
      maxLength: 35
    executionRule:
      use: required
      maxLength: 140
    reference:
      use: required
      maxLength: 35
    referenceType:
      maxLength: 35
    referenceIssuer:
      maxLength: 35
    creditorName:
      use: required
      maxLength: 70
    creditorId:
      use: none

stoplist:
  cron:
    # the top of every hour of every day
    expression: 0 0 * * * *

not-confirmed-consent-expiration:
  cron:
    # the top of every hour of every day
    expression: 0 0 * * * *

not-confirmed-payment-expiration:
  cron:
    # the top of every hour of every day
    expression: 0 0 * * * *

used-non-recurring-consent-expiration:
  cron:
    # the top of every hour of every day
    expression: 0 0 * * * *

consent:
  cron:
    expression: 0 0 1 * * ?

scheduler:
  pool:
    size: 30

#---
#spring:
#  profiles: default
#  application.name: ledgers-xs2a-gateway
#  # These datasource information are provided for the consent db
#  jackson:
#    serialization:
#      write_dates_as_timestamps: false
#      wrap-root-value: true

---
spring:
  profiles: austria

validation:
  payment:
    creditorId:
      use: optional
      maxLength: 35


---
spring:
  profiles: dev

logging.level.org.postgresql: INFO
logging.level.org.hibernate.SQL: WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: WARN
logging.level.org.springframework: INFO

management.endpoints.web.exposure.include: "*"
management.endpoints.web.exposure.exclude: env,beans

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: full

logging.level.de.adorsys.ledgers.middleware: DEBUG
logging.level.org.adorsys.ledgers.consent: DEBUG
logging.level.de.adorsys.ledgers.xs2a.api: DEBUG
logging.level.de.adorsys.ledgers.rest: DEBUG
logging.level.de.adorsys.psd2.consent: DEBUG
